/* Copyright (c) 2006 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

using System;
using System.Collections.Generic;
using System.Text;
using Google.GData.Client;
using System.Xml;
using Google.GData.Extensions;
using System.IO;
using System.Xml.Serialization;

namespace Google.GData.Health
{
    /// <summary>
    /// Represents a single ContinuityOfCareRecord provided by Google Health.
    /// </summary>
    public class ContinuityOfCareRecord
    {
        /// <summary>
        /// "The CCR and all Data Objects contained within the CCR must have ObjectIDs. 
        /// The CCR Document Object ID is generated by the originating entity/system to 
        /// uniquely identify each explicit instance of a CCR. The uniqueness of this 
        /// ObjectID is defined within the generating system and must be unique to and 
        /// within each CCR and ideally should be unique across the universe of all CCRs."
        /// (TABLE A1.1 CCR Data Fields Spreadsheet, page 9 of the Standard Specification Continuity of Care Record (CCR)).
        /// </summary>
        [XElemBinding("CCRDocumentObjectID", BindingType.Value)]
        public string CCRDocumentObjectID { get; set; }

        /// <summary>
        /// Gets or sets the CCR Document Language.
        /// </summary>
        [XElemBinding("Language", BindingType.Element)]
        public CodedValue Language { get; set; }

        /// <summary>
        /// Gets or sets the continuity of care record version.
        /// </summary>
        [XElemBinding("Version", BindingType.Element)]
        public Version Version { get; set; }

        /// <summary>
        /// Gets or sets the date representing the last modified date 
        /// for this document is sent out by Google.
        /// </summary>
        [XElemBinding("DateTime", BindingType.Element)]
        public DateTimeContent LastModified { get; set; }

        /// <summary>
        /// Gets or sets the the patient actor associated with the CCR.
        /// </summary>
        [XElemBinding("Patient", BindingType.Element)]
        public Patient Patient { get; set; }

        /// <summary>
        /// Gets or sets the continuity of care record body.
        /// </summary>
        [XElemBinding("Body", BindingType.Element)]
        public Body Body { get; set; }

        /// <summary>
        /// Gets or sets the continuity of care record actors.
        /// </summary>
        [XmlArrayItem("Actor")]
        [XElemBinding("Actors", BindingType.Elements)]
        public List<Actor> Actors { get; set; }

        public static ContinuityOfCareRecord FromAtomEntry(AtomEntry entry)
        {
            if (entry != null)
            {
                var factory = entry.FindExtension("ContinuityOfCareRecord", "urn:astm-org:CCR");
                if (factory != null)
                {
                    XmlExtension extension = factory as XmlExtension;
                    XmlDocument xDoc = new XmlDocument();
					xDoc.ImportNode(extension, true);
                    ElementBuilder<ContinuityOfCareRecord> recordBuilder = new ElementBuilder<ContinuityOfCareRecord>();
                    return recordBuilder.FromElement(xDoc.DocumentElement);
                }
            }

            return null;
        }
    }
}
